sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-120
env:
  global:
    -
      # LTD_AWS_ID
      secure: dUO2JUcptCDw1RcT/URgMRQibI5h3GCLuS9BDJhwZ3Z3RRlzOmkLLa5uAZHV8J1F2A9kNCbqhliCllUaZVssH6xgal8MnJ97DcyeAGobzkOSLnO9dtFbkjGc1xEx6ar0qouarJq0TJ0/Y+POAOfPz9IQgumUH3LM4MeNHqcllVwWX1X1gq6FGghjcN2zcAMCcsrk9m3tGanLoapctozQ79NZCqs2PuTDW3E+5Be05nfgW/jGQsEi0zfHtu+AkKfDtn7vyEDXohw1Ys44RJKxeWXqktiAo+KJS/Y4vmPXAvYa6QjWLkhTi2vuGcD10BZ7IJAOcJxm3Xz9UPwQDUYe+Q7L9OCdhbNDj26eHmdHZBXVoJdFSLoTxFeau5Qh9yPe3esoVw86FkG4nNaQZ1RrK7EFArzQ3JJzR5B07JJsbSlpuOJFT22hvR01e7n+pYPycRN92GmIvVS4rXa711/anViJVgLLPjwZvS6SdcBcVSo8i/q0jcfZMtg+ScPL8afGvNEk8cRTHEG1IlOq/O9f+5kH6eiYO+NZ1HlTRq164KUHn0ln8aMDdTheMA8MjBOOIvoOqa56BW13KpOyrse6ZJntizUxvxm8MbPaR7nuf2EHwAWvNrRDSxnBTEwGh3Z7DWoMmSwcm1uT8WyTQzt4qbGrPPKsN59TCN95UnGYQmY=
    -
      # LTD_AWS_SECRET
      secure: DCeWzu1PIO/Xb26OimLb4YPDpHaxt86cceu3Ab09YNWpsJnFXb1+aKAjWT/93Tgw99EzosEjhPgIUDJZRSKhVN7pwXsjwRg3NwfZA7QIMcSXKPgVpS08gfOscrjundRdOnyHhvU1SRK7G1eD1Slia87TdZxr1Sk/SjdOSK1GKUYLKA8ldZwa4i8zsCloobd6VGI5UjlWrwOAxTBQeT6ydcEC2im3FK9WXQ0MEbx2cGynxsfp0rCLe5IxqAN0Rrl2P/Cr2EW0+dgW95VW1MATKwGbgIxEL3H3sM13uiZ+zd/4auSM32iebUHQaL3310lzOs2TT06B26D1mP649n1MARDwJsZ70koHUwMQ/Xf3nQOUZc+CPBz8ard4D4mH29smvPWxAf5zXd/e58eh+6MER7xTexm9RfXOkjlZfROc2McuZU8Ezrm+97RCRB8n55Rbb/pM4pFenXTeWhlSBRXxrkcgeIJlqVMaP4X0VdTKQTMvVHz9pw/lopGmoOJhhDmIUlQOTZMkL1crlPDe5Yo7cQ+Rex4UpVYb+/crtwprQo/cxGhcQdNDBP0qYBZ+N8x2AA9d/kEchAOY+rNuTxbfUCo2lABa9D/fG0Y1jUey5ldJb9JunP6sVY2NIyRLMlpvWonGLdvAwrDqU4H0cj+SEwHKdo5/AWYd4h4QSyNBv0o=
    -
      # LTD_USERNAME
      secure: ULYpBLYDqia1VydUlohjyrj7ysdt/b1mEfMztahnEAeuJI7yujOoy3DMyLs9EIcmLfYEQZu019w2aYMpnpDnST7WmpRaRuYjyfuOn03Mm9j2xZg+6JuaxYw2lWGBGjgQzWqh61Fb/+1khmatZdEtU/CH6bESJws1Z8qHCA+QIGCBoOc1+yAuxryc4CkELFP0cPM0AB9QnO+31DLSWkaiNYkNBlravvUJd7NNCItmjQa2eXZFFhM7ywBcx8Yq44KHwsuXDFDn+dfqaMSUuyO9MH9uCtpimG7htxJSuIsYBBMA7Jqnx9ymjp+b0FX2OYGECvUGY1q/d2mWzUDXVxV+XX18Y83097jhFMO+LftIDHMOfIRdZLjmGtiyCdW82nzB7tqxs6eCMljbk0yY3piJkm/ypq5pXwafWh7SCQTEjhFilV6CE70SpeTyWDhbdT2JGFj9efDFeFQkdv/oJ+ZXl2EfbP1AHOEM0xm50LLRqAiSy7DfLWUJP2134ARXqq2YQlbexxlGtto9ifj5drpc/UULH9CeZ8CC6pLer6eu091xg6wGrCUF8oYek9SlgLnDN3CvNaKFFOr/YNkHlNjynhvHLc6ATWu9ohOd3dkQdTH/iU2jDLjm/7UnvR7yEsqtr/4Nu+kShrGkpP1NtCNV4Sr4rKTVXTKy9c3lvvSpgks=
    -
      # LTD_PASSWORD
      secure: foWqKFcGh6KDtv5rYNxyunzikdd4OMFX0PkOA+2YORHFkQzbYRyh38GdwBqVcM6CbpDsYHdqgb6oh6RnbV3B51VvzVfJGeywmZ7q92PxSUpCkCkfkc3if41deYqgPmFbqc53TbQ9mfsncym93vfKeUICSyRr2XpVw+XUluD93D8aqF5IRgwzkYiOIbh6uOClN9iEiBrmjbiuXsMJ+y+tS9ajEY+mBlc5K6qxsD/PzjmUBPvkdiFwiInuSbIViNrZ2q3/tB3+AWm7ggTECdkxQJwl5QDAVUrTYaaxkudsHSTa5bCnbMVBzcrxwXUr1pDd6ByqRASKQOhYaWEYhnXigzeBDYWe2o+QDTUmCatty0m1JAQXOd6i2+j6he9bZlS3ha8d7APOaTIRoF+hh/fcKdciE4vqey4SUpdue0/nAKXC9DKhqKQJzS+RWyXI2bXvf4BVhc86Yj6W3lViDdA0T7kuR+qXGDS1Q4YxX3G3uWJYewKQGpd2uXJGcnnY9FmxmbAWBqoqnGP7NOjcTqpLNerdvdpLS++6sLW1T0XIsQLh86A0DF4Whcy/Av+erSJZ1WLYdKvI49ICVD1omfkYoqa3ZJBbN7n+riu8OlPjH988yzLxLGL+abT9J7AkXpDUqEStBb2ueQsTuW6TxFa1Kk9TmIiz4fS2wVtAkL9yMCE=
